name: Deploy Jekyll Site

on:
  push:
    branches:
      - main
      - preview/*  # Deploy preview branches separately
  pull_request:
    branches:
      - main  # Ensure PRs run the build process but don't deploy
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Setup Bundler Cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-

      - name: Install Jekyll and Dependencies
        run: |
          bundle config set path 'vendor/bundle'
          bundle install
          bundle clean

      - name: Build Jekyll Site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Report Build Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const state = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: state,
              context: 'report-build-status',
              description: state === 'success' ? 'Build completed successfully' : 'Build failed'
            });

      - name: Deploy to GitHub Pages (Main)
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site

      - name: Deploy to GitHub Pages (Preview)
        if: startsWith(github.ref, 'refs/heads/preview/')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-preview
          publish_dir: ./_site
